set['jenkins']['server']['plugins'] = [ 'greenballs',
                                        'github-api',
                                        'mailer',
                                        'github-oauth',
                                        'github',
                                        'git',
                                        'git-parameter',
                                        'token-macro',
                                        'multiple-scms',
                                        'ssh-credentials',
                                        'credentials',
                                        'parameterized-trigger',
                                        'scm-api',
                                        'promoted-builds',
                                        'git-client',
                                        'phing',
                                        'progress-bar-column-plugin',
                                        'beer',
                                        'chucknorris',
                                        'build-monitor-plugin',
                                        'disk-usage',
                                        'analysis-core',
                                        'pmd',
                                        'jdepend',
                                        'dry',
                                        'checkstyle',
                                        'jquery',
                                        'build-pipeline-plugin',
                                        'dashboard-view',
                                        'buildgraph-view',
                                        'jobConfigHistory',
                                        'scm-sync-configuration',
                                        'JiraTestResultReporter',
                                        'jira',
                                        'jenkins-jira-issue-updater',
                                      ]
default['jenkins']['server']['config']['uri'] = ''
default['jenkins']['server']['config']['branch'] = 'master'
